remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
title: Mariyam Aqeel
description: First-year CSE student passionate about software development, data structures, and building efficient solutions to real-world problems.
